CELERYD_NODES="worker1"
DJANGO_SETTINGS_MODULE="{{ root_package_name }}.settings.{{ goal }}"
CELERY_BIN="{{ remote_virtualenv_dir }}/bin/celery"
CELERY_APP="{{ root_package_name }}"
CELERYD_CHDIR="{{ remote_current_path }}"
CELERYD_OPTS="--time-limit=86400 --concurrency=1 --maxtasksperchild=1"
CELERYD_LOG_FILE="/var/log/celery/%N.log"
CELERYD_PID_FILE="/var/run/celery/%N.pid"
CELERYD_USER="{{ remote_owner }}"
CELERYD_GROUP="{{ remote_group }}"
CELERY_CREATE_DIRS=1
CELERYD_LOG_LEVEL="INFO"
